### ISSUE TITLE
Замечания по 1.2 (clocks)

### ISSUE THREAD

**Issue by sergey-shambir** [Relz/BPA#1]
- Вместо собственной константы PI следует использовать стандартную `M_PI` из заголовка `<cmath>`: [http://stackoverflow.com/questions/806145/](http://stackoverflow.com/questions/806145/)
- Вместо `struct Point` можно использовать `sf::Vector2f` или `sf::Vector2u`
- Странное сокращение слова: `Point coors;`
- Почему `initializeDashesAndNumbers` возвращает bool, причём всегда true?

**Comment by Relz** [comment]
Исправлено
